# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edc1824620e44b6e1a9ca259d1087f79b6ae3e19c09ef8a995fb6c756de7f8cb3a5713e8ce326230b4ae09bf0246f30525ed81bbb47186dd6134c3eee6475c25

test:
  secret_key_base: d5d1eb7b5a068d22f64a3c41eea9b8b9ec79cff5371b78b32f183267b44c1daef68be15d6575a26386db9e55014cf208a2888b84fa706f421cfb50ecd0920966

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
